POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email":"heli712@gmail.com",
    "pwd" : "hli"
}

###
POST http://localhost:8080/inside HTTP/1.1

### 
POST http://localhost:8080/register HTTP/1.1
content-type: application/json 

{
    "email" : "heli712@gmail.com",
    "name" : "heli",
    "pwd" : "heli"
}

###
POST http://localhost:8080/updateDetails HTTP/1.1
content-type: application/json

{
    "cname": "tester",
    "email": "test@gmail.com",
    "DOB" : "1998/12/7",
    "nickname" : "test",
    "mobileNo" : "6692241133",
    "customerId" : "4",
    "about" : "I like food"
}

###
POST http://localhost:8080/resturant/register HTTP/1.1
content-type: application/json

{
    "rname" : "subway",
    "email" : "subway@gmail.com",
    "pwd" : "subway"
}

###
POST http://localhost:8080/resturant/login HTTP/1.1
content-type: application/json

{
    "email" : "dominos@gmail.com",
    "pwd" : "dominos"
}

###
POST http://localhost:8080/resturant/updateDetails HTTP/1.1
content-type: application/json

{
    "rname" : "paneera bread",
    "email" : "pb@gmail.com",
    "mobileNo" : "6691140044",
    "resturantId" : "3",
    "cdes" : "delicious cookie",
    "timings" : "9 to 10"
}

###
POST http://localhost:8080/dish/add HTTP/1.1
content-type: application/json

{
    "dname" : "pasta",
    "ingredients" : "pasta sauce, vegetables",
    "price" : "6.99",
    "resturantId" : "3"
}

###
POST http://localhost:8080/dish/find HTTP/1.1
content-type: application/json

{
    "name" : "honest"
}

###
POST http://localhost:8080/dish/findresturant HTTP/1.1
content-type: application/json

{
    "resturantId" : "7"
}

###
POST http://localhost:8080/resturant/all HTTP/1.1
content-type: application/json

{
    "rname" : "sub"
}

###
GET http://localhost:8080/key/custome HTTP/1.1

###
POST http://localhost:8080/dish/delete HTTP/1.1
content-type: application/json

{
    "resturantId" : "1",
    "dname" : "garlic bread"
}

###
POST http://localhost:8080/resturant/location HTTP/1.1
content-type: application/json

{
    "city" : ""
}

###
POST http://localhost:8080/favorite/add HTTP/1.1
content-type: application/json

{
    "customerId" : "2",
    "resturantId" : "5"
}

###
POST http://localhost:8080/favorite/show HTTP/1.1
content-type: application/json

{
    "customerId" : "2"
}

###
POST http://localhost:8080/favorite/remove HTTP/1.1
content-type: application/json

{
    "customerId" : "2",
    "resturantId" : "4"
}

###
POST http://localhost:8080/customer/addtocart HTTP/1.1
content-type: application/json

{
    "customerId" : "2",
    "resturantId" : "4",
    "dishId" : "32",
    "quantity" : 1
}

###
POST http://localhost:8080/resturant/orderdetails HTTP/1.1
content-type: application/json

{
    "resturantId": "13"
}

###
POST  http://3.84.44.207:8080/login HTTP/1.1
content-type: application/json

{
    "email" : "heli@gmail.com",
    "password" : "heli"
}